-- Android HUD agent for CC: Androids + CC:Tweaked 1.20.2
-- Generated by the Turtle HUD server. Config values are injected on download.
--
-- Install:   wget run <server>/android.lua?token=<token>
-- Persist:   wget <server>/android.lua?token=<token> startup
-- Run:       hud [name]
--
-- Transport mirrors turtle/hud.lua (same protocol: hello/welcome/state/cmd/
-- result/log) - only the command surface differs: androids expose the global
-- `android` table instead of `turtle`.

-- single endpoint: the install file on github is re-baked whenever the
-- tunnel gets a new url, so when dials keep failing the reconnect loop
-- re-reads that file and adopts the endpoint it carries now. everything
-- runs on github + the auto-managed cloudflare tunnel, nothing else.
local WS_URLS = { "wss://prix-ministries-closer-seemed.trycloudflare.com/android" }
local WS_URL = WS_URLS[1]
local GITHUB_SRC =
    "https://raw.githubusercontent.com/ArcTechTech/TurtleTest/main/android.lua"
local TOKEN = "447004d3aa68ca41"

local args = { ... }
local CID = os.getComputerID()
local NAME = args[1] or os.getComputerLabel() or ("android-" .. tostring(CID))

if android == nil then
    printError("This program must run on a CC: Androids android,")
    printError("not a plain turtle/computer.")
    return
end

-- ------------------------------------------------------------------ state --
local ws = nil
local outbox = {}
local jobs = {}
local stopFlag = false
local status = "starting"
local connected = false
local dirtyState = true

-- androids report ABSOLUTE world coords every tick - no odometry/odometer.
local pos = { x = 0, y = 0, z = 0 }
local known = false
local fuel = 0
local fuelLimit = 10000        -- BaseAndroidEntity.maxFuel
local health = 0
local task = "idle"
local hand = ""                -- "name xN" of the main hand
local followUUID = nil         -- set while in follow mode
local followAge = 0            -- ticks since the follow target was acquired

-- forward declarations -------------------------------------------------------
local renderScreen

local function push(o)
    outbox[#outbox + 1] = o
    os.queueEvent("android_flush")
end

local logs = {}
local function log(msg, level)
    msg = tostring(msg)
    logs[#logs + 1] = msg
    if #logs > 50 then table.remove(logs, 1) end
    push({ t = "log", msg = msg, level = level or "info" })
    renderScreen()
end

renderScreen = function()
    if not term then return end
    term.setCursorPos(1, 1)
    term.setTextColor(connected and colors.green or colors.red)
    print(string.format("[HUD] %s", connected and ("online " .. WS_URL)
        or "offline"))
    term.setTextColor(colors.white)
    print("name   " .. NAME)
    print(string.format("fuel   %s/%s", tostring(fuel),
        tostring(fuelLimit)))
    print(string.format("pos    %s,%s,%s", tostring(pos.x), tostring(pos.y),
        tostring(pos.z)))
    if health > 0 then
        print(string.format("health %s", tostring(health)))
    end
    term.setTextColor(colors.yellow)
    print("status " .. status)
    print("task   " .. task)
    if hand ~= "" then
        print("hand   " .. hand)
    end
    if followUUID then
        print("follow yes")
    end
    term.setTextColor(colors.white)
end

-- --------------------------------------------------------------- refresh ---
--- Poll the android's live state. Some of these are mainThread calls (they
--- yield), which is fine: we only ever call this from a coroutine.
local function refresh()
    local ok, info = pcall(android.getSelf)
    if ok and type(info) == "table" then
        local x, y, z = tonumber(info.posX), tonumber(info.posY),
            tonumber(info.posZ)
        if x and y and z then
            pos.x, pos.y, pos.z = math.floor(x), math.floor(y), math.floor(z)
            known = true
        end
        if tonumber(info.health) then health = tonumber(info.health) end
    end

    local okF, f = pcall(android.fuelLevel)
    if okF and tonumber(f) then fuel = tonumber(f) end

    local okT, tk = pcall(android.currentTask)
    if okT and tk ~= nil then task = tostring(tk) end

    local okH, hn, hc = pcall(android.getHandInfo, "main")
    if okH and type(hn) == "string" and hn ~= "Air" and hn ~= "" then
        hand = hn .. (tonumber(hc) and (" x" .. hc) or "")
    else
        hand = ""
    end
end

local function pushState()
    push({
        t = "state", name = NAME, label = os.getComputerLabel(),
        fuel = fuel, fuelLimit = fuelLimit,
        pos = { x = pos.x, y = pos.y, z = pos.z }, known = known,
        status = status, task = task, health = health, hand = hand,
        follow = followUUID ~= nil,
    })
    dirtyState = false
end

local function flushOutbox()
    if not ws then return true end
    while #outbox > 0 do
        local m = table.remove(outbox, 1)
        local ok = pcall(ws.send, textutils.serializeJSON(m))
        if not ok then
            table.insert(outbox, 1, m)
            return false
        end
    end
    return true
end

-- ------------------------------------------------------- android calls -----
--- Call an android API and normalize CC-Androids' return convention.
--- The mod reports failures as `(true, "msg")` and successes as `(false,
--- "msg")` / `("msg")` / `()`, and throws LuaException for hard errors:
---   throws            -> (false, errmsg)
---   (true, "msg")     -> (false, msg)     [mod's failure flag]
---   (false, "msg")    -> (true, msg)      [mod's success + detail]
---   ("msg")           -> (true, msg)
---   (table)           -> (true, "ok", table)   [query result]
---   ()                -> (true, "ok")
local function callA(fn, ...)
    local packed = table.pack(pcall(fn, ...))
    if not packed[1] then
        return false, tostring(packed[2])
    end
    local a, b = packed[2], packed[3]
    if type(a) == "table" then
        return true, "ok", a
    end
    if a == true and type(b) == "string" then
        return false, b
    end
    if packed.n <= 1 then
        return true, "ok"
    end
    if a == false and type(b) == "string" then
        return true, b
    end
    if type(a) == "string" then
        return true, a
    end
    local parts = {}
    for i = 2, packed.n do parts[#parts + 1] = tostring(packed[i]) end
    return true, #parts > 0 and table.concat(parts, " ") or "ok"
end

local function xyzOf(a)
    local x, y, z = tonumber(a.x), tonumber(a.y), tonumber(a.z)
    if not x or not y or not z then return nil end
    return math.floor(x), math.floor(y), math.floor(z)
end

--- Resolve the closest player (used by follow / attack when no uuid given).
local function closestPlayer()
    local ok, msg, p = callA(android.getClosestPlayer)
    if ok and type(p) == "table" and p.uuid then return p end
    return nil, (not ok and msg) or "no player nearby"
end

-- ----------------------------------------------------------------- jobs ----
local function runCmd(cmd, a)
    a = a or {}

    -- movement: async - the android pathfinds on its own, progress shows up
    -- in currentTask() and the position on the next state tick ------------ --
    if cmd == "moveTo" then
        local x, y, z = xyzOf(a)
        if not x then return false, "need x, y, z" end
        followUUID = nil            -- a manual move cancels follow
        return callA(android.moveTo, x, y, z)
    end
    if cmd == "goTo" then
        local u = a.uuid or a.target
        if not u then return false, "need uuid" end
        return callA(android.goTo, tostring(u))
    end
    if cmd == "follow" then
        local p, err = closestPlayer()
        if not p then return false, err end
        followUUID = p.uuid
        followAge = 0
        -- kick off the first leg right away
        pcall(android.goTo, followUUID)
        dirtyState = true
        return true, "following " .. tostring(p.name or p.uuid)
    end
    if cmd == "attack" then
        local u = a.uuid
        if not u then
            local p, err = closestPlayer()
            if not p then return false, err end
            u = p.uuid
        end
        return callA(android.attack, tostring(u))
    end
    if cmd == "stop" or cmd == "cancelTask" then
        followUUID = nil
        dirtyState = true
        return callA(android.cancelTask)
    end

    -- blocks ---------------------------------------------------------------- --
    if cmd == "breakBlock" then
        local x, y, z = xyzOf(a)
        if not x then return false, "need x, y, z" end
        return callA(android.breakBlock, x, y, z)
    end
    if cmd == "useBlock" then
        local x, y, z = xyzOf(a)
        if not x then return false, "need x, y, z" end
        return callA(android.useBlock, x, y, z)
    end
    if cmd == "useEntity" then
        local u = a.uuid or a.target
        if not u then return false, "need uuid" end
        return callA(android.useEntity, tostring(u))
    end

    -- inventory / fuel ------------------------------------------------------- --
    if cmd == "refuel" then
        local ok, msg = callA(android.refuel, tonumber(a.amt) or nil)
        refresh()
        dirtyState = true
        return ok, msg
    end
    if cmd == "pickup" then
        local ok, msg = callA(android.pickup, a.type)
        refresh()
        dirtyState = true
        return ok, msg
    end
    if cmd == "dropItem" then
        local ok, msg = callA(android.dropItem)
        refresh()
        dirtyState = true
        return ok, msg
    end
    if cmd == "equipSlot" then
        local idx = tonumber(a.index)
        if not idx then return false, "need index" end
        local ok, msg = callA(android.equipSlot, idx)
        refresh()
        dirtyState = true
        return ok, msg
    end
    if cmd == "swapHands" then
        local ok, msg = callA(android.swapHands)
        refresh()
        dirtyState = true
        return ok, msg
    end

    -- misc ------------------------------------------------------------------- --
    if cmd == "chat" or cmd == "say" then
        local m = a.msg or a.text
        if not m or m == "" then return false, "no message" end
        return callA(android.sendChatMessage, tostring(m))
    end
    if cmd == "face" then
        return callA(android.changeFace, tostring(a.face or a.name or "default"))
    end

    -- queries (return data back to the dashboard) ---------------------------- --
    if cmd == "task" then
        refresh()
        return true, task, { task = task }
    end
    if cmd == "info" then
        refresh()
        dirtyState = true
        return true, "ok", { pos = pos, fuel = fuel, task = task,
            health = health, hand = hand, follow = followUUID ~= nil }
    end
    if cmd == "players" then
        local p, err = closestPlayer()
        if not p then return false, err end
        return true, tostring(p.name or p.uuid), { player = p }
    end
    if cmd == "mobs" then
        local ok, msg, m = callA(android.getNearbyMobs, a.type)
        return ok, msg, m
    end

    -- arbitrary code ----------------------------------------------------------- --
    if cmd == "lua" then
        local code = a.code
        if not code or code == "" then return false, "no code" end
        local fn, err = load(code, "remote", "t", _ENV)
        if not fn then return false, tostring(err) end
        local prints = {}
        local oldPrint = print
        print = function(...)
            local parts = {}
            for i = 1, select("#", ...) do
                parts[#parts + 1] = tostring(select(i, ...))
            end
            prints[#prints + 1] = table.concat(parts, " ")
            if #prints > 20 then table.remove(prints, 1) end
        end
        local results = table.pack(pcall(fn))
        print = oldPrint
        local rets = {}
        for i = 2, results.n do rets[#rets + 1] = tostring(results[i]) end
        if results[1] then
            return true, #rets > 0 and table.concat(rets, " ") or "ok",
                { prints = prints, returns = rets }
        end
        return false, tostring(results[2]), { prints = prints }
    end

    return false, "unknown command: " .. tostring(cmd)
end

-- --------------------------------------------------------------- coroutines --
local function handleMessage(raw)
    local m = textutils.unserializeJSON(raw)
    if not m or type(m) ~= "table" then return end
    if m.t == "cmd" then
        if m.cmd == "stop" then
            stopFlag = true
            jobs = {}
            followUUID = nil
            pcall(android.cancelTask)
            push({ t = "result", seq = m.seq, ok = true, msg = "stopping" })
            log("stop requested", "warn")
        else
            jobs[#jobs + 1] = { seq = m.seq, cmd = m.cmd, args = m.args }
        end
    elseif m.t == "welcome" then
        connected = true
        status = "idle"
        refresh()
        log("connected as " .. tostring(m.name or NAME), "ok")
        pushState()
    elseif m.t == "error" then
        error(tostring(m.msg), 0)
    end
end

--- Sole websocket writer + event pump. Returning ends the session.
local function reader()
    local timer = os.startTimer(1)
    while true do
        local ev = { os.pullEvent() }
        local e = ev[1]
        if e == "android_flush" then
            if not flushOutbox() then return end
        elseif e == "timer" and ev[2] == timer then
            -- refresh every second: position, fuel and the current AI task
            refresh()
            -- follow mode: re-acquire the target periodically, and re-issue
            -- goTo whenever the android goes idle (it finished the last leg)
            if followUUID then
                followAge = followAge + 1
                if followAge % 5 == 0 then
                    local p = closestPlayer()
                    if p and p.uuid then followUUID = p.uuid end
                end
                if task == "idle" then
                    pcall(android.goTo, followUUID)
                end
                dirtyState = true
            end
            pushState()
            if not flushOutbox() then return end
            renderScreen()
            timer = os.startTimer(1)
        elseif e == "websocket_message" and ev[2] == WS_URL then
            handleMessage(ev[3])
            if not flushOutbox() then return end
        elseif (e == "websocket_closed" or e == "websocket_failure") and
            ev[2] == WS_URL then
            return
        end
    end
end

local function worker()
    while true do
        local job
        if #jobs > 0 then job = table.remove(jobs, 1) end
        if job then
            stopFlag = false
            status = job.cmd
            dirtyState = true
            renderScreen()
            local packed = { pcall(runCmd, job.cmd, job.args) }
            local ok, msg, data
            if packed[1] then
                ok, msg, data = packed[2], packed[3], packed[4]
            else
                ok, msg = false, tostring(packed[2])
            end
            status = "idle"
            push({ t = "result", seq = job.seq, ok = ok and true or false,
                   msg = msg or "", data = data })
            dirtyState = true
            renderScreen()
            if not ok then
                log(tostring(job.cmd) .. ": " .. tostring(msg), "warn")
            end
        else
            sleep(0.1)
        end
    end
end

-- ----------------------------------------------------------------- session --
local function waitForWelcome()
    -- send hello directly so it is always the first frame on the wire,
    -- ahead of any queued log lines (those flush once reader() starts)
    ws.send(textutils.serializeJSON(
        { t = "hello", token = TOKEN, name = NAME, cid = CID, ver = 1,
          kind = "android" }))
    local timer = os.startTimer(15)
    while true do
        local ev = { os.pullEvent() }
        local e = ev[1]
        if e == "websocket_message" and ev[2] == WS_URL then
            local m = textutils.unserializeJSON(ev[3])
            if m and m.t == "welcome" then
                handleMessage(ev[3])
                return
            elseif m and m.t == "error" then
                handleMessage(ev[3])
            end
        elseif e == "timer" and ev[2] == timer then
            error("server sent no welcome")
        elseif (e == "websocket_closed" or e == "websocket_failure") and
            ev[2] == WS_URL then
            error("connection closed")
        end
    end
end

local function session()
    local w, err = http.websocket(WS_URL)
    if not w then error(tostring(err), 0) end
    ws = w
    connected = false
    waitForWelcome()
    parallel.waitForAny(reader, worker)
end

-- --------------------------------------------------------------------- run --
print("Android HUD starting...")
print("server: " .. WS_URL)

local urlIdx = 1
local backoff = 1
local fails = 0
while true do
    status = "connecting"
    renderScreen()
    local ok, err = pcall(session)
    connected = false
    jobs = {}
    stopFlag = false
    followUUID = nil
    if ws then pcall(ws.close) end
    ws = nil
    outbox = {}
    if not ok then
        status = "reconnecting"
        printError(tostring(err))
        log("disconnected: " .. tostring(err), "error")
        fails = fails + 1
        urlIdx = urlIdx % #WS_URLS + 1
        WS_URL = WS_URLS[urlIdx]
        -- after a few failed dials the tunnel url has almost certainly
        -- rotated: re-read the github install file (re-baked on every
        -- rotation) and adopt whatever endpoint it carries now
        if fails % 3 == 0 then
            pcall(function()
                local h = http.get(GITHUB_SRC)
                if not h then return end
                local body = h.readAll()
                pcall(h.close)
                local u = body and body:match('WS_URLS = { "(.-)"')
                if u and u ~= WS_URL then
                    WS_URL = u
                    WS_URLS[1] = u
                    urlIdx = 1
                    print("[HUD] endpoint refreshed: " .. u)
                    log("endpoint refreshed: " .. u, "info")
                end
            end)
        end
        renderScreen()
        sleep(backoff)
        backoff = math.min(backoff * 2, 10)
    else
        urlIdx = 1
        WS_URL = WS_URLS[urlIdx]
        fails = 0
        backoff = 1
        sleep(0.5)
    end
end
