-- Android HUD agent for CC: Androids + CC:Tweaked 1.20.2
-- Generated by the Turtle HUD server. Config values are injected on download.
--
-- Install:   wget run <server>/android.lua?token=<token>
-- Persist:   wget <server>/android.lua?token=<token> startup
-- Run:       hud [name]
--
-- Transport mirrors turtle/hud.lua (same protocol: hello/welcome/state/cmd/
-- result/log) - only the command surface differs: androids expose the global
-- `android` table instead of `turtle`.

-- single endpoint: the install file on github is re-baked whenever the
-- tunnel gets a new url, so when dials keep failing the reconnect loop
-- re-reads that file and adopts the endpoint it carries now. everything
-- runs on github + the auto-managed cloudflare tunnel, nothing else.
local WS_URLS = { "wss://preservation-prison-harbour-friday.trycloudflare.com/android" }
local WS_URL = WS_URLS[1]
local GITHUB_SRC =
    "https://raw.githubusercontent.com/ArcTechTech/TurtleTest/main/android.lua"
local TOKEN = "447004d3aa68ca41"

local args = { ... }
local CID = os.getComputerID()
local NAME = args[1] or os.getComputerLabel() or ("android-" .. tostring(CID))

if android == nil then
    printError("This program must run on a CC: Androids android,")
    printError("not a plain turtle/computer.")
    return
end

-- ------------------------------------------------------------------ state --
local ws = nil
local outbox = {}
local jobs = {}
local stopFlag = false
local status = "starting"
local connected = false
local dirtyState = true
-- sensor contacts (nearest player + visible mobs) - declared before
-- pushState so the state builder sees the same binding sense() fills
local seen = {}

-- androids report ABSOLUTE world coords every tick - no odometry/odometer.
local pos = { x = 0, y = 0, z = 0 }
local known = false
local fuel = 0
local fuelLimit = 10000        -- BaseAndroidEntity.maxFuel
local health = 0
local task = "idle"
local hand = ""                -- "name xN" of the main hand
local followUUID = nil         -- set while in follow mode
local followAge = 0            -- ticks since the follow target was acquired

-- combat preferences: usernames that must NEVER be targeted (the operator's
-- own name lives here), plus the guard post + mode. the post and the list
-- survive reboots through the local state file; the mode itself is armed
-- from the dashboard and stops with the stop button.
local ignoreNames = {}
local guardPost = nil          -- {x,y,z} marked with setguard
local guardOn = false          -- guard mode armed (guard)
local guardRadius = 16         -- acquire radius around the post
local guardTarget = "all"      -- all | players | mobs

-- forward declarations -------------------------------------------------------
local renderScreen

local function push(o)
    outbox[#outbox + 1] = o
    os.queueEvent("android_flush")
end

local logs = {}
local function log(msg, level)
    msg = tostring(msg)
    logs[#logs + 1] = msg
    if #logs > 50 then table.remove(logs, 1) end
    push({ t = "log", msg = msg, level = level or "info" })
    renderScreen()
end

renderScreen = function()
    if not term then return end
    term.setCursorPos(1, 1)
    term.setTextColor(connected and colors.green or colors.red)
    print(string.format("[HUD] %s", connected and ("online " .. WS_URL)
        or "offline"))
    term.setTextColor(colors.white)
    print("name   " .. NAME)
    print(string.format("fuel   %s/%s", tostring(fuel),
        tostring(fuelLimit)))
    print(string.format("pos    %s,%s,%s", tostring(pos.x), tostring(pos.y),
        tostring(pos.z)))
    if health > 0 then
        print(string.format("health %s", tostring(health)))
    end
    term.setTextColor(colors.yellow)
    print("status " .. status)
    print("task   " .. task)
    if hand ~= "" then
        print("hand   " .. hand)
    end
    if followUUID then
        print("follow yes")
    end
    if guardOn and guardPost then
        print(string.format("guard  %d,%d,%d r=%d",
            math.floor(guardPost.x), math.floor(guardPost.y),
            math.floor(guardPost.z), guardRadius))
    end
    term.setTextColor(colors.white)
end

-- --------------------------------------------------------------- refresh ---
--- Poll the android's live state. Some of these are mainThread calls (they
--- yield), which is fine: we only ever call this from a coroutine.
local function refresh()
    local ok, info = pcall(android.getSelf)
    if ok and type(info) == "table" then
        local x, y, z = tonumber(info.posX), tonumber(info.posY),
            tonumber(info.posZ)
        if x and y and z then
            pos.x, pos.y, pos.z = math.floor(x), math.floor(y), math.floor(z)
            known = true
        end
        if tonumber(info.health) then health = tonumber(info.health) end
    end

    local okF, f = pcall(android.fuelLevel)
    if okF and tonumber(f) then fuel = tonumber(f) end

    local okT, tk = pcall(android.currentTask)
    if okT and tk ~= nil then task = tostring(tk) end

    local okH, hn, hc = pcall(android.getHandInfo, "main")
    if okH and type(hn) == "string" and hn ~= "Air" and hn ~= "" then
        hand = hn .. (tonumber(hc) and (" x" .. hc) or "")
    else
        hand = ""
    end
end

local function pushState()
    push({
        t = "state", name = NAME, label = os.getComputerLabel(),
        fuel = fuel, fuelLimit = fuelLimit,
        pos = { x = pos.x, y = pos.y, z = pos.z }, known = known,
        status = status, task = task, health = health, hand = hand,
        follow = followUUID ~= nil, seen = seen,
        guard = (guardOn and guardPost) and
            { x = guardPost.x, y = guardPost.y, z = guardPost.z,
              r = guardRadius, target = guardTarget } or nil,
        ignore = table.concat(ignoreNames, ","),
    })
    dirtyState = false
end

local function flushOutbox()
    if not ws then return true end
    while #outbox > 0 do
        local m = table.remove(outbox, 1)
        local ok = pcall(ws.send, textutils.serializeJSON(m))
        if not ok then
            table.insert(outbox, 1, m)
            return false
        end
    end
    return true
end

-- ------------------------------------------------------- android calls -----
--- Call an android API and normalize CC-Androids' return convention.
--- The mod reports failures as `(true, "msg")` and successes as `(false,
--- "msg")` / `("msg")` / `()`, and throws LuaException for hard errors:
---   throws            -> (false, errmsg)
---   (true, "msg")     -> (false, msg)     [mod's failure flag]
---   (false, "msg")    -> (true, msg)      [mod's success + detail]
---   ("msg")           -> (true, msg)
---   (table)           -> (true, "ok", table)   [query result]
---   ()                -> (true, "ok")
local function callA(fn, ...)
    local packed = table.pack(pcall(fn, ...))
    if not packed[1] then
        return false, tostring(packed[2])
    end
    local a, b = packed[2], packed[3]
    if type(a) == "table" then
        return true, "ok", a
    end
    if a == true and type(b) == "string" then
        return false, b
    end
    if packed.n <= 1 then
        return true, "ok"
    end
    if a == false and type(b) == "string" then
        return true, b
    end
    if type(a) == "string" then
        return true, a
    end
    local parts = {}
    for i = 2, packed.n do parts[#parts + 1] = tostring(packed[i]) end
    return true, #parts > 0 and table.concat(parts, " ") or "ok"
end

local function xyzOf(a)
    local x, y, z = tonumber(a.x), tonumber(a.y), tonumber(a.z)
    if not x or not y or not z then return nil end
    return math.floor(x), math.floor(y), math.floor(z)
end

--- Resolve the closest player (used by follow / attack when no uuid given).
local function closestPlayer()
    local ok, msg, p = callA(android.getClosestPlayer)
    if ok and type(p) == "table" and p.uuid then return p end
    return nil, (not ok and msg) or "no player nearby"
end

-- --------------------------------------------------------------- persist ----
-- guard post + ignore list live in their own small file so a reboot never
-- forgets where the android was told to stand (or who not to shoot).
local STATE_FILE = "/.android_hud_state"

local function saveLocal()
    if not (fs and fs.open) then return end
    pcall(function()
        local h = fs.open(STATE_FILE, "w")
        if not h then return end
        h.writeLine(textutils.serializeJSON({
            ignore = ignoreNames, post = guardPost,
            r = guardRadius, tgt = guardTarget,
        }))
        h.close()
    end)
end

local function loadLocal()
    if not (fs and fs.exists and fs.exists(STATE_FILE)) then return end
    pcall(function()
        local h = fs.open(STATE_FILE, "r")
        if not h then return end
        local raw = h.readLine()
        h.close()
        local s = raw and textutils.unserializeJSON(raw)
        if type(s) ~= "table" then return end
        if type(s.ignore) == "table" then ignoreNames = s.ignore end
        if type(s.post) == "table" and s.post.x and s.post.y and s.post.z then
            guardPost = { x = s.post.x, y = s.post.y, z = s.post.z }
        end
        if tonumber(s.r) then guardRadius = tonumber(s.r) end
        if type(s.tgt) == "string" then guardTarget = s.tgt end
    end)
end
loadLocal()

-- ------------------------------------------------------------- targeting ----
-- the mod matches a type filter with `contains()` against the entity's
-- REGISTRY id (SensorModule.getTypePredicate), so "spider" also catches
-- cave_spider and "skeleton" wither_skeleton. these are registry-id
-- substrings of hostile mobs - a cow can never match one.
local HOSTILE_TYPES = {
    "zombie", "husk", "drowned", "skeleton", "stray", "bogged", "spider",
    "creeper", "witch", "enderman", "blaze", "ghast", "slime", "magma_cube",
    "pillager", "vindicator", "evoker", "vex", "ravager", "guardian",
    "phantom", "silverfish", "shulker", "piglin", "hoglin", "zoglin",
    "warden", "wither", "breeze",
}

--- Is this name on the never-target list? (case-insensitive)
local function isIgnored(name)
    if not name then return false end
    local n = string.lower(tostring(name))
    for _, ig in ipairs(ignoreNames) do
        if ig == n then return true end
    end
    return false
end

local function dist2(ax, ay, az, bx, by, bz)
    local dx, dy, dz = ax - bx, ay - by, az - bz
    return dx * dx + dy * dy + dz * dz
end

--- Closest hostile mob in sensor range (line of sight, 10/30 blocks).
local function closestHostile()
    local best, bestd = nil, math.huge
    for _, t in ipairs(HOSTILE_TYPES) do
        local ok, _, m = callA(android.getClosestMob, t)
        if ok and type(m) == "table" and m.uuid and m.uuid ~= "" then
            local x = tonumber(m.posX)
            local y = tonumber(m.posY)
            local z = tonumber(m.posZ)
            if x and y and z then
                local d = dist2(x, y, z, pos.x, pos.y, pos.z)
                if d < bestd then best, bestd = m, d end
            end
        end
    end
    if not best then return nil, "no hostile nearby" end
    return best
end

--- Player candidates: the closest player (100 blocks, through walls) plus
--- everyone visible in line of sight. the mod's mob query with type
--- "player" matches the player entity's registry id, so one ignored name
--- never hides the other players behind it.
local function playerCandidates()
    local out, seenU = {}, {}
    local function add(p)
        if type(p) == "table" and p.uuid and not seenU[p.uuid] then
            seenU[p.uuid] = true
            out[#out + 1] = p
        end
    end
    add(closestPlayer())
    local ok, _, list = callA(android.getNearbyMobs, "player")
    if ok and type(list) == "table" then
        for _, e in ipairs(list) do add(e) end
    end
    return out
end

--- Nearest entry of `list` to a point, or nil when the list is empty.
local function nearestTo(x, y, z, list)
    local best, bd = nil, math.huge
    for _, e in ipairs(list) do
        local ex = tonumber(e.posX)
        local ey = tonumber(e.posY)
        local ez = tonumber(e.posZ)
        if ex and ey and ez then
            local d = dist2(ex, ey, ez, x, y, z)
            if d < bd then best, bd = e, d end
        end
    end
    return best
end

-- --------------------------------------------------------------- sensors ---
--- What the android can currently see: nearest player (100 blocks, through
--- walls) plus everything living in line of sight within 10 blocks. Pushed
--- with every state tick so the dashboard map draws live contacts.

local function seenEntry(kind, e)
    local x, y, z = tonumber(e.posX), tonumber(e.posY), tonumber(e.posZ)
    if not x or not y or not z then return nil end
    return { kind = kind, uuid = tostring(e.uuid or ""),
        name = tostring(e.name or "?"), x = math.floor(x),
        y = math.floor(y), z = math.floor(z), hp = tonumber(e.health) }
end

local function sense()
    local out = {}
    local p = closestPlayer()
    local pu = p and p.uuid or nil
    local entry = pu and seenEntry("player", p) or nil
    if entry then out[#out + 1] = entry end
    local ok, _, list = callA(android.getNearbyMobs)
    if ok and type(list) == "table" then
        for _, e in ipairs(list) do
            if type(e) == "table" and e.uuid ~= pu then
                local en = seenEntry("mob", e)
                if en then out[#out + 1] = en end
            end
        end
    end
    seen = out
end

-- ----------------------------------------------------------------- jobs ----
local function runCmd(cmd, a)
    a = a or {}

    -- movement: async - the android pathfinds on its own, progress shows up
    -- in currentTask() and the position on the next state tick ------------ --
    if cmd == "moveTo" then
        local x, y, z = xyzOf(a)
        if not x then return false, "need x, y, z" end
        followUUID = nil            -- a manual move cancels follow
        return callA(android.moveTo, x, y, z)
    end
    if cmd == "goTo" then
        local u = a.uuid or a.target
        if not u then return false, "need uuid" end
        return callA(android.goTo, tostring(u))
    end
    if cmd == "follow" then
        local p, err = closestPlayer()
        if not p then return false, err end
        followUUID = p.uuid
        followAge = 0
        -- kick off the first leg right away
        pcall(android.goTo, followUUID)
        dirtyState = true
        return true, "following " .. tostring(p.name or p.uuid)
    end
    if cmd == "attack" then
        local u = a.uuid
        if u then
            -- explicit target (map click): swing at exactly that entity
            return callA(android.attack, tostring(u))
        end
        -- no uuid: pick a target by mode. "mobs" (the default) only ever
        -- selects HOSTILE mobs - never a player, never a cow; "players"
        -- selects the nearest player that isn't on the ignore list.
        local mode = tostring(a.target or a.mode or "mobs")
        if mode == "players" then
            local cands = {}
            for _, p in ipairs(playerCandidates()) do
                if not isIgnored(p.name) then cands[#cands + 1] = p end
            end
            if #cands == 0 then
                return false, "no player nearby (or all on the ignore list)"
            end
            local best = nearestTo(pos.x, pos.y, pos.z, cands)
            return callA(android.attack, tostring(best.uuid))
        end
        local m, err = closestHostile()
        if not m then return false, err end
        return callA(android.attack, tostring(m.uuid))
    end
    if cmd == "setignore" then
        local names = tostring(a.names or a.name or "")
        ignoreNames = {}
        for w in string.gmatch(names, "[^,%s]+") do
            ignoreNames[#ignoreNames + 1] = string.lower(w)
        end
        saveLocal()
        dirtyState = true
        return true, #ignoreNames == 0 and "ignore list cleared"
            or ("ignoring " .. table.concat(ignoreNames, ", "))
    end
    if cmd == "setguard" then
        if not known then return false, "no position yet" end
        guardPost = { x = pos.x, y = pos.y, z = pos.z }
        saveLocal()
        dirtyState = true
        return true, string.format("guard post set at %d,%d,%d",
            math.floor(pos.x), math.floor(pos.y), math.floor(pos.z))
    end
    if cmd == "clearguard" then
        guardPost = nil
        guardOn = false
        saveLocal()
        dirtyState = true
        return true, "guard post cleared"
    end
    if cmd == "guard" then
        if not guardPost then
            return false, "no guard post set (use setguard first)"
        end
        guardRadius = math.floor(math.max(4, math.min(128,
            tonumber(a.radius) or guardRadius)))
        local tg = tostring(a.target or guardTarget or "all")
        if tg == "hostiles" then tg = "mobs" end
        if tg ~= "players" and tg ~= "mobs" then tg = "all" end
        guardTarget = tg
        guardOn = true
        saveLocal()
        dirtyState = true
        return true, string.format("guarding %d,%d,%d r=%d (%s)",
            math.floor(guardPost.x), math.floor(guardPost.y),
            math.floor(guardPost.z), guardRadius, guardTarget)
    end
    if cmd == "stop" or cmd == "cancelTask" then
        followUUID = nil
        dirtyState = true
        return callA(android.cancelTask)
    end

    -- blocks ---------------------------------------------------------------- --
    if cmd == "breakBlock" then
        local x, y, z = xyzOf(a)
        if not x then return false, "need x, y, z" end
        return callA(android.breakBlock, x, y, z)
    end
    if cmd == "useBlock" then
        local x, y, z = xyzOf(a)
        if not x then return false, "need x, y, z" end
        return callA(android.useBlock, x, y, z)
    end
    if cmd == "useEntity" then
        local u = a.uuid or a.target
        if not u then return false, "need uuid" end
        return callA(android.useEntity, tostring(u))
    end

    -- inventory / fuel ------------------------------------------------------- --
    if cmd == "refuel" then
        local ok, msg = callA(android.refuel, tonumber(a.amt) or nil)
        refresh()
        dirtyState = true
        return ok, msg
    end
    if cmd == "pickup" then
        local ok, msg = callA(android.pickup, a.type)
        refresh()
        dirtyState = true
        return ok, msg
    end
    if cmd == "dropItem" then
        local ok, msg = callA(android.dropItem)
        refresh()
        dirtyState = true
        return ok, msg
    end
    if cmd == "equipSlot" then
        local idx = tonumber(a.index)
        if not idx then return false, "need index" end
        local ok, msg = callA(android.equipSlot, idx)
        refresh()
        dirtyState = true
        return ok, msg
    end
    if cmd == "swapHands" then
        local ok, msg = callA(android.swapHands)
        refresh()
        dirtyState = true
        return ok, msg
    end

    -- misc ------------------------------------------------------------------- --
    if cmd == "chat" or cmd == "say" then
        local m = a.msg or a.text
        if not m or m == "" then return false, "no message" end
        return callA(android.sendChatMessage, tostring(m))
    end
    if cmd == "face" then
        return callA(android.changeFace, tostring(a.face or a.name or "default"))
    end

    -- queries (return data back to the dashboard) ---------------------------- --
    if cmd == "task" then
        refresh()
        return true, task, { task = task }
    end
    if cmd == "info" then
        refresh()
        dirtyState = true
        return true, "ok", { pos = pos, fuel = fuel, task = task,
            health = health, hand = hand, follow = followUUID ~= nil }
    end
    if cmd == "players" then
        local p, err = closestPlayer()
        if not p then return false, err end
        return true, tostring(p.name or p.uuid), { player = p }
    end
    if cmd == "mobs" then
        local ok, msg, m = callA(android.getNearbyMobs, a.type)
        return ok, msg, m
    end
    if cmd == "scan" then
        sense()
        dirtyState = true
        local pl, mb = 0, 0
        for _, e in ipairs(seen) do
            if e.kind == "player" then pl = pl + 1 else mb = mb + 1 end
        end
        return true, string.format("%d player(s), %d mob(s) in sight",
            pl, mb), { seen = seen }
    end

    -- arbitrary code ----------------------------------------------------------- --
    if cmd == "lua" then
        local code = a.code
        if not code or code == "" then return false, "no code" end
        local fn, err = load(code, "remote", "t", _ENV)
        if not fn then return false, tostring(err) end
        local prints = {}
        local oldPrint = print
        print = function(...)
            local parts = {}
            for i = 1, select("#", ...) do
                parts[#parts + 1] = tostring(select(i, ...))
            end
            prints[#prints + 1] = table.concat(parts, " ")
            if #prints > 20 then table.remove(prints, 1) end
        end
        local results = table.pack(pcall(fn))
        print = oldPrint
        local rets = {}
        for i = 2, results.n do rets[#rets + 1] = tostring(results[i]) end
        if results[1] then
            return true, #rets > 0 and table.concat(rets, " ") or "ok",
                { prints = prints, returns = rets }
        end
        return false, tostring(results[2]), { prints = prints }
    end

    return false, "unknown command: " .. tostring(cmd)
end

--- One guard beat: engage the nearest allowed target within radius of the
--- post, or hold the post when nobody's around. Runs on the 1s tick.
local function guardTick()
    if not guardOn or not guardPost then return end
    -- already swinging: let the attack task finish (the mod's own guard
    -- program works the same way - one target at a time). the real task
    -- is called "attacking"; "attack"/"attackingMob" kept for safety.
    if task == "attacking" or task == "attack" or task == "attackingMob" then
        return
    end
    local r2 = guardRadius * guardRadius
    local wantPlayers = guardTarget ~= "mobs" and guardTarget ~= "hostiles"
    local wantMobs = guardTarget ~= "players"
    local best, bd = nil, math.huge
    local function consider(e)
        if type(e) ~= "table" or not e.uuid or isIgnored(e.name) then return end
        local x = tonumber(e.posX)
        local y = tonumber(e.posY)
        local z = tonumber(e.posZ)
        if not x or not y or not z then return end
        -- radius is measured from the POST, not from the android
        local d = dist2(x, y, z, guardPost.x, guardPost.y, guardPost.z)
        if d > r2 then return end
        if d < bd then best, bd = e, d end
    end
    if wantPlayers then
        for _, p in ipairs(playerCandidates()) do consider(p) end
    end
    if wantMobs then
        for _, t in ipairs(HOSTILE_TYPES) do
            local ok, _, m = callA(android.getClosestMob, t)
            if ok then consider(m) end
        end
    end
    if best then
        pcall(android.attack, tostring(best.uuid))
        dirtyState = true
    elseif task == "idle" then
        -- nobody to hit: stand on the post (only re-path when clearly off it)
        local d = dist2(pos.x, pos.y, pos.z,
            guardPost.x, guardPost.y, guardPost.z)
        if d > 4 then
            pcall(android.moveTo, guardPost.x, guardPost.y, guardPost.z)
            dirtyState = true
        end
    end
end

-- --------------------------------------------------------------- coroutines --
local function handleMessage(raw)
    local m = textutils.unserializeJSON(raw)
    if not m or type(m) ~= "table" then return end
    if m.t == "cmd" then
        if m.cmd == "stop" then
            stopFlag = true
            jobs = {}
            followUUID = nil
            guardOn = false
            pcall(android.cancelTask)
            push({ t = "result", seq = m.seq, ok = true, msg = "stopping" })
            log("stop requested", "warn")
        else
            jobs[#jobs + 1] = { seq = m.seq, cmd = m.cmd, args = m.args }
        end
    elseif m.t == "welcome" then
        connected = true
        status = "idle"
        refresh()
        log("connected as " .. tostring(m.name or NAME), "ok")
        pushState()
    elseif m.t == "error" then
        error(tostring(m.msg), 0)
    end
end

--- Sole websocket writer + event pump. Returning ends the session.
local function reader()
    local timer = os.startTimer(1)
    while true do
        local ev = { os.pullEvent() }
        local e = ev[1]
        if e == "android_flush" then
            if not flushOutbox() then return end
        elseif e == "timer" and ev[2] == timer then
            -- refresh every second: position, fuel and the current AI task
            refresh()
            pcall(sense)      -- live contacts for the map feed
            -- follow mode: re-acquire the target periodically, and re-issue
            -- goTo whenever the android goes idle (it finished the last leg)
            if followUUID then
                followAge = followAge + 1
                if followAge % 5 == 0 then
                    local p = closestPlayer()
                    if p and p.uuid then followUUID = p.uuid end
                end
                if task == "idle" then
                    pcall(android.goTo, followUUID)
                end
                dirtyState = true
            end
            -- guard mode: re-scan the post's neighbourhood every beat and
            -- engage (or walk back to the post when the area is clear)
            if guardOn then guardTick() end
            pushState()
            if not flushOutbox() then return end
            renderScreen()
            timer = os.startTimer(1)
        elseif e == "websocket_message" and ev[2] == WS_URL then
            handleMessage(ev[3])
            if not flushOutbox() then return end
        elseif (e == "websocket_closed" or e == "websocket_failure") and
            ev[2] == WS_URL then
            return
        end
    end
end

local function worker()
    while true do
        local job
        if #jobs > 0 then job = table.remove(jobs, 1) end
        if job then
            stopFlag = false
            status = job.cmd
            dirtyState = true
            renderScreen()
            local packed = { pcall(runCmd, job.cmd, job.args) }
            local ok, msg, data
            if packed[1] then
                ok, msg, data = packed[2], packed[3], packed[4]
            else
                ok, msg = false, tostring(packed[2])
            end
            status = "idle"
            push({ t = "result", seq = job.seq, ok = ok and true or false,
                   msg = msg or "", data = data })
            dirtyState = true
            renderScreen()
            if not ok then
                log(tostring(job.cmd) .. ": " .. tostring(msg), "warn")
            end
        else
            sleep(0.1)
        end
    end
end

-- ----------------------------------------------------------------- session --
local function waitForWelcome()
    -- send hello directly so it is always the first frame on the wire,
    -- ahead of any queued log lines (those flush once reader() starts)
    ws.send(textutils.serializeJSON(
        { t = "hello", token = TOKEN, name = NAME, cid = CID, ver = 1,
          kind = "android" }))
    local timer = os.startTimer(15)
    while true do
        local ev = { os.pullEvent() }
        local e = ev[1]
        if e == "websocket_message" and ev[2] == WS_URL then
            local m = textutils.unserializeJSON(ev[3])
            if m and m.t == "welcome" then
                handleMessage(ev[3])
                return
            elseif m and m.t == "error" then
                handleMessage(ev[3])
            end
        elseif e == "timer" and ev[2] == timer then
            error("server sent no welcome")
        elseif (e == "websocket_closed" or e == "websocket_failure") and
            ev[2] == WS_URL then
            error("connection closed")
        end
    end
end

local function session()
    local w, err = http.websocket(WS_URL)
    if not w then error(tostring(err), 0) end
    ws = w
    connected = false
    waitForWelcome()
    parallel.waitForAny(reader, worker)
end

-- --------------------------------------------------------------------- run --
print("Android HUD starting...")
print("server: " .. WS_URL)

local urlIdx = 1
local backoff = 1
local fails = 0
while true do
    status = "connecting"
    renderScreen()
    local ok, err = pcall(session)
    connected = false
    jobs = {}
    stopFlag = false
    followUUID = nil
    if ws then pcall(ws.close) end
    ws = nil
    outbox = {}
    if not ok then
        status = "reconnecting"
        printError(tostring(err))
        log("disconnected: " .. tostring(err), "error")
        fails = fails + 1
        urlIdx = urlIdx % #WS_URLS + 1
        WS_URL = WS_URLS[urlIdx]
        -- after a few failed dials the tunnel url has almost certainly
        -- rotated: re-read the github install file (re-baked on every
        -- rotation) and adopt whatever endpoint it carries now
        if fails % 3 == 0 then
            pcall(function()
                local h = http.get(GITHUB_SRC)
                if not h then return end
                local body = h.readAll()
                pcall(h.close)
                local u = body and body:match('WS_URLS = { "(.-)"')
                if u and u ~= WS_URL then
                    WS_URL = u
                    WS_URLS[1] = u
                    urlIdx = 1
                    print("[HUD] endpoint refreshed: " .. u)
                    log("endpoint refreshed: " .. u, "info")
                end
            end)
        end
        renderScreen()
        sleep(backoff)
        backoff = math.min(backoff * 2, 10)
    else
        urlIdx = 1
        WS_URL = WS_URLS[urlIdx]
        fails = 0
        backoff = 1
        sleep(0.5)
    end
end
