-- Turtle HUD agent for CC: Tweaked (Minecraft 1.20.1)
-- Generated by the Turtle HUD server. Config values are injected on download.
--
-- Install:   wget run <server>/hud.lua?token=<token>
-- Persist:   wget <server>/hud.lua?token=<token> startup
-- Run:       hud [name]

-- endpoint list: primary first (cloudflare quick tunnel - its url rotates on
-- every restart) then the permanent tailscale funnel. the reconnect loop
-- rotates through this list, so a tunnel restart never needs a reinstall.
local WS_URLS = { "https://santa-application-proud-martial.trycloudflare.com/turtle",
    "wss://desktop-09fqktu.tail9a2d18.ts.net:8443/turtle" }
local WS_URL = WS_URLS[1]
local TOKEN = "447004d3aa68ca41"

local args = { ... }
local CID = os.getComputerID()
local NAME = args[1] or os.getComputerLabel() or ("turtle-" .. tostring(CID))

-- ------------------------------------------------------------------ state --
local ws = nil
local outbox = {}
local jobs = {}
local stopFlag = false
local status = "starting"
local connected = false
local dirtyState = true

-- compass facing: 0 = north (-Z), 1 = east (+X), 2 = south (+Z), 3 = west (-X)
local FWD = {
    [0] = { x = 0, z = -1 },
    [1] = { x = 1, z = 0 },
    [2] = { x = 0, z = 1 },
    [3] = { x = -1, z = 0 },
}
local FACE_NAME = { [0] = "north", [1] = "east", [2] = "south", [3] = "west" }

local facing = 0
local pos = { x = 0, y = 0, z = 0 }   -- odometry (0,0,0 = program start)
local known = false                   -- true once calibrated / gps fix
local home = nil
local scanMode = "off"                -- "off" | "walls" | "all" (set per job)

-- block reporting (all map data lives on the server / your PC, not here)
local pending = {}                    -- {x,y,z,nameIndex} batches
local pendingNames = {}               -- name -> index in current batch
local seen = {}                       -- "x,y,z" -> name (skip re-inspect)
local seenCount = 0
local oreTargets = {}                 -- "x,y,z" -> {x,y,z} autoMine detours
local gcur = { layer = 0, lane = 0, cell = 0 }  -- autoMine grid cursor
local farmA = nil                    -- farm corner A {x,y,z} (setfarm, click 1)
local farmB = nil                    -- opposite farm corner (setfarm, click 2)
local fcur = { lane = 0, cell = 0 }  -- farm walk cursor

-- local persistence: keep home / odometer / grid cursor on disk so a crash,
-- reboot or re-install doesn't force a recalibrate + sethome every time ------
local SAVE_PATH = "/.turtle_hud_state"
local function saveLocal()
    pcall(function()
        local f = fs.open(SAVE_PATH, "w")
        if not f then return end
        f.write(textutils.serializeJSON({
            pos = { x = pos.x, y = pos.y, z = pos.z },
            facing = facing, known = known, home = home, grid = gcur,
            farmA = farmA, farmB = farmB, fcur = fcur,
        }))
        f.close()
    end)
end
local function loadLocal()
    pcall(function()
        local f = fs.open(SAVE_PATH, "r")
        if not f then return end
        local raw = f.readAll()
        f.close()
        local s = raw and textutils.unserializeJSON(raw)
        if type(s) ~= "table" then return end
        if type(s.pos) == "table" then
            pos = { x = tonumber(s.pos.x) or pos.x,
                    y = tonumber(s.pos.y) or pos.y,
                    z = tonumber(s.pos.z) or pos.z }
        end
        if tonumber(s.facing) then facing = tonumber(s.facing) % 4 end
        known = s.known == true or known
        local h = type(s.home) == "table" and s.home or nil
        if h and tonumber(h.x) and tonumber(h.y) and tonumber(h.z) then
            home = { x = tonumber(h.x), y = tonumber(h.y), z = tonumber(h.z) }
        end
        if type(s.grid) == "table" then
            gcur = { layer = tonumber(s.grid.layer) or gcur.layer,
                     lane = tonumber(s.grid.lane) or gcur.lane,
                     cell = tonumber(s.grid.cell) or gcur.cell }
        end
        local function loadCorner(v)
            if type(v) ~= "table" then return nil end
            local x, y, z = tonumber(v.x), tonumber(v.y), tonumber(v.z)
            if not (x and y and z) then return nil end
            return { x = x, y = y, z = z }
        end
        farmA = loadCorner(s.farmA) or farmA
        farmB = loadCorner(s.farmB) or farmB
        if type(s.fcur) == "table" then
            fcur = { lane = tonumber(s.fcur.lane) or 0,
                     cell = tonumber(s.fcur.cell) or 0 }
        end
    end)
end

-- forward declarations -------------------------------------------------------
local flushBlocks
local renderScreen

local function fmtNum(n)
    if n == math.floor(n) then return string.format("%d", n) end
    return tostring(n)
end

local function bkey(x, y, z)
    return fmtNum(x) .. "," .. fmtNum(y) .. "," .. fmtNum(z)
end

local function nameMatches(name, pat)
    if not pat or pat == "" or pat == false then return false end
    if type(pat) ~= "string" then return false end
    if pat:find("*", 1, true) then
        local escaped = pat:gsub("([%^%$%(%)%%%.%[%]%+%-%?])", "%%%1")
        local rx = "^" .. escaped:gsub("%*", ".*") .. "$"
        return name:match(rx) ~= nil
    end
    return name == pat
end

local function push(o)
    outbox[#outbox + 1] = o
    os.queueEvent("hud_flush")
end

local logs = {}
local function log(msg, level)
    msg = tostring(msg)
    logs[#logs + 1] = msg
    if #logs > 50 then table.remove(logs, 1) end
    push({ t = "log", msg = msg, level = level or "info" })
    renderScreen()
end

renderScreen = function()
    if not term then return end
    term.setCursorPos(1, 1)
    term.setTextColor(connected and colors.green or colors.red)
    print(string.format("[HUD] %s", connected and ("online " .. WS_URL)
        or "offline"))
    term.setTextColor(colors.white)
    print("name   " .. NAME)
    local f = turtle.getFuelLevel()
    print(string.format("fuel   %s/%s", tostring(f),
        tostring(turtle.getFuelLimit())))
    print(string.format("pos    %s,%s,%s %s%s", fmtNum(pos.x), fmtNum(pos.y),
        fmtNum(pos.z), FACE_NAME[facing], known and "" or " (?)"))
    term.setTextColor(colors.yellow)
    print("status " .. status)
    term.setTextColor(colors.white)
    term.setCursorPos(1, 8)
end

-- ------------------------------------------------------------ block map ----
flushBlocks = function()
    if #pending == 0 then return end
    local names = {}
    for i = 1, #pendingNames do names[i] = pendingNames[i] end
    local add = pending
    pending, pendingNames = {}, {}
    push({ t = "blocks", names = names, add = add })
end

--- Ore heuristic (vanilla …_ore plus modded names that contain "ore").
local function isOreName(n)
    if type(n) ~= "string" then return false end
    local base = n:match("([^:]+)$") or n
    return base:find("ore", 1, true) ~= nil
end

local function addBlock(x, y, z, name)
    if not name then return end
    local key = bkey(x, y, z)
    if seen[key] == name then return end
    seen[key] = name
    seenCount = seenCount + 1
    if seenCount > 40000 then seen, seenCount = {}, 0 end
    -- auto-mine bookkeeping: a fresh ore sighting becomes a detour target,
    -- and a cell corrected away from ore (mined or re-scanned) drops its own
    if oreTargets[key] then
        if not isOreName(name) then oreTargets[key] = nil end
    elseif isOreName(name) then
        oreTargets[key] = { x = math.floor(x), y = math.floor(y),
            z = math.floor(z) }
    end
    local ni = pendingNames[name]
    if not ni then
        ni = #pendingNames + 1
        pendingNames[ni] = name
    end
    pending[#pending + 1] = { math.floor(x), math.floor(y), math.floor(z), ni }
    if #pending >= 150 then flushBlocks() end
end

local function invList()
    local inv = {}
    for i = 1, 16 do
        local d = turtle.getItemDetail(i)
        if d then
            inv[#inv + 1] = { s = i, name = d.name, count = d.count }
        end
    end
    return inv
end

local function pushState()
    push({
        t = "state", name = NAME, label = os.getComputerLabel(),
        fuel = turtle.getFuelLevel(), fuelLimit = turtle.getFuelLimit(),
        pos = { x = pos.x, y = pos.y, z = pos.z }, known = known,
        facing = facing, status = status, sel = turtle.getSelectedSlot(),
        home = home, inv = invList(), crafty = turtle.craft ~= nil,
        left = peripheral.getType("left"), right = peripheral.getType("right"),
    })
    dirtyState = false
end

local function flushOutbox()
    if not ws then return true end
    while #outbox > 0 do
        local m = table.remove(outbox, 1)
        local ok = pcall(ws.send, textutils.serializeJSON(m))
        if not ok then
            table.insert(outbox, 1, m)
            return false
        end
    end
    return true
end

-- --------------------------------------------------------------- movement --
local function checkStop()
    if stopFlag then error("Stopped", 0) end
end

local function refuelScan(target)
    local lvl = turtle.getFuelLevel()
    if lvl == "unlimited" then return false end
    target = target or turtle.getFuelLimit()
    if lvl >= target then return false end
    local prev = turtle.getSelectedSlot()
    local refueled = false
    for i = 1, 16 do
        local l = turtle.getFuelLevel()
        if l == "unlimited" or l >= target then break end
        turtle.select(i)
        if turtle.refuel(0) then
            refueled = true
            while true do
                local l2 = turtle.getFuelLevel()
                if l2 == "unlimited" or l2 >= target then break end
                if not turtle.refuel(1) then break end
            end
        end
    end
    turtle.select(prev)
    dirtyState = true
    return refueled
end

local function ensureFuel()
    local lvl = turtle.getFuelLevel()
    if lvl == "unlimited" then return end
    if lvl < 2 then
        refuelScan(math.min(turtle.getFuelLimit(), 200))
        lvl = turtle.getFuelLevel()
    end
    if lvl < 1 then error("Out of fuel", 0) end
end

local function targetOf(dir)
    if dir == "up" then return pos.x, pos.y + 1, pos.z end
    if dir == "down" then return pos.x, pos.y - 1, pos.z end
    local f = FWD[facing]
    return pos.x + f.x, pos.y, pos.z + f.z
end

local function digFn(dir)
    if dir == "up" then return turtle.digUp end
    if dir == "down" then return turtle.digDown end
    return turtle.dig
end

local function inspectFn(dir)
    if dir == "up" then return turtle.inspectUp end
    if dir == "down" then return turtle.inspectDown end
    return turtle.inspect
end

local function doInspect(dir)
    local ok, data = inspectFn(dir)()
    if ok and type(data) == "table" and data.name then return data.name end
    return nil
end

--- Break the block in `dir`; records what was there and marks the cell air.
local function digBlock(dir)
    local scanned = scanMode ~= "off"
    local tx, ty, tz = targetOf(dir)
    if scanned then
        local before = doInspect(dir)
        if before then addBlock(tx, ty, tz, before) end
    end
    local ok, err = digFn(dir)()
    if ok then
        dirtyState = true
        if scanned then addBlock(tx, ty, tz, "minecraft:air") end
    end
    return ok, err
end

--- Look at the four cells around the turtle (turning for the side looks).
local function scanSides(includeFrontBack)
    local orig = facing
    local function look(dir)
        while facing ~= dir do
            turtle.turnLeft()
            facing = (facing + 3) % 4
        end
        local f = FWD[facing]
        -- record air as well: a rescan must be able to CORRECT cells that
        -- changed in-world, otherwise the map drifts out of sync forever
        addBlock(pos.x + f.x, pos.y, pos.z + f.z,
            doInspect("front") or "minecraft:air")
    end
    addBlock(pos.x, pos.y + 1, pos.z, doInspect("up") or "minecraft:air")
    addBlock(pos.x, pos.y - 1, pos.z, doInspect("down") or "minecraft:air")
    look((orig + 3) % 4)   -- left
    look((orig + 1) % 4)   -- right
    if includeFrontBack then
        look(orig)
        look((orig + 2) % 4)
    end
    while facing ~= orig do
        turtle.turnLeft()
        facing = (facing + 3) % 4
    end
end

local function turnLeft()
    turtle.turnLeft()
    facing = (facing + 3) % 4
    -- record what we now face and push the new heading to the dashboard
    -- immediately (waiting on the 1s state tick made turns feel laggy)
    local f = FWD[facing]
    addBlock(pos.x + f.x, pos.y, pos.z + f.z, doInspect("front") or "minecraft:air")
    flushBlocks()
    pushState()
end

local function turnRight()
    turtle.turnRight()
    facing = (facing + 1) % 4
    local f = FWD[facing]
    addBlock(pos.x + f.x, pos.y, pos.z + f.z, doInspect("front") or "minecraft:air")
    flushBlocks()
    pushState()
end

local function faceTo(dir)
    local diff = (dir - facing) % 4
    if diff == 1 then turnRight()
    elseif diff == 2 then turnRight(); turnRight()
    elseif diff == 3 then turnLeft() end
end

local function updatePos(dir)
    if dir == "up" then pos.y = pos.y + 1
    elseif dir == "down" then pos.y = pos.y - 1
    else
        local f = FWD[facing]
        if dir == "forward" then
            pos.x, pos.z = pos.x + f.x, pos.z + f.z
        elseif dir == "back" then
            pos.x, pos.z = pos.x - f.x, pos.z - f.z
        end
    end
    dirtyState = true
end

--- Move one block. autoDig breaks whatever is in the way (except behind).
local function move(dir, autoDig)
    checkStop()
    ensureFuel()
    local ok, err = turtle[dir]()
    -- CC reports a blocked path as "Movement obstructed"
    if not ok and autoDig and dir ~= "back" and err and
        tostring(err):lower():find("obstruct", 1, true) then
        digBlock(dir == "forward" and "front" or dir)
        checkStop()
        ensureFuel()
        ok, err = turtle[dir]()
    end
    if not ok then
        -- a blocked move still tells us what is there: record the obstacle,
        -- otherwise driving into a wall never maps the wall ("front missed")
        if dir ~= "back" then
            local d = dir == "forward" and "front" or dir
            local name = doInspect(d)
            if name then
                local tx, ty, tz = targetOf(d)
                addBlock(tx, ty, tz, name)
                -- flush NOW: if a higher layer errors right after this,
                -- queued blocks would otherwise ride along unflushed
                flushBlocks()
            end
        end
        return false, err
    end
    updatePos(dir)
    -- live mapping (gambit pattern): the occupied cell and the cells
    -- down/up/ahead are recorded on every move - as solids OR air - so
    -- travel, goto and manual driving all grow/correct the server-side map.
    addBlock(pos.x, pos.y, pos.z, "minecraft:air")
    local dn = doInspect("down")
    addBlock(pos.x, pos.y - 1, pos.z, dn or "minecraft:air")
    local upHere = doInspect("up")
    addBlock(pos.x, pos.y + 1, pos.z, upHere or "minecraft:air")
    local fw = doInspect("front")
    local f = FWD[facing]
    addBlock(pos.x + f.x, pos.y, pos.z + f.z, fw or "minecraft:air")
    -- move telemetry leaves instantly: queued blocks + state flush right
    -- here instead of waiting for the reader's 1s tick
    flushBlocks()
    pushState()
    return true
end

--- Move and dig through obstacles (used by navigation / mining).
local function moveStrict(dir)
    local ok, err = move(dir, true)
    if not ok then error(err or "cannot move", 0) end
end

-- ------------------------------------------------------------- navigation --
local function stepTo(dir)
    faceTo(dir)
    moveStrict("forward")
end

local function goTo(x, y, z)
    local guard = 0
    while pos.y ~= y do
        moveStrict(pos.y < y and "up" or "down")
        guard = guard + 1
        if guard > 512 then error("goto failed (y)", 0) end
    end
    while pos.x ~= x do stepTo(pos.x < x and 1 or 3) end
    while pos.z ~= z do stepTo(pos.z < z and 2 or 0) end
end

-- ------------------------------------------------------- side helpers ------
local function resolveDir(d)
    if d == "up" or d == "down" then return d end
    return "front"
end

local function dropTo(dir, count)
    local fn = dir == "up" and turtle.dropUp or
        dir == "down" and turtle.dropDown or turtle.drop
    return fn(count)
end

local function suckFrom(dir)
    local fn = dir == "up" and turtle.suckUp or
        dir == "down" and turtle.suckDown or turtle.suck
    return fn(nil)
end

local function invTotal()
    local n = 0
    for i = 1, 16 do n = n + turtle.getItemCount(i) end
    return n
end

-- ------------------------------------------------------------- crafting ----
--- Simple craft: arrange the recipe, stash anything in the way (chest if one
--- is adjacent, otherwise dropped on the ground), craft, then suck it back.
local function craftJob(a)
    if not turtle.craft then
        return false, "Needs a Crafty Turtle (craft a turtle together with " ..
            "a crafting table)"
    end
    local grid = a.grid or {}
    local cells, inWindow = {}, {}
    for r = 1, 3 do
        for c = 1, 3 do inWindow[(r - 1) * 4 + c] = true end
    end
    for r = 1, #grid do
        local row = grid[r] or {}
        for c = 1, #row do
            local pat = row[c]
            if type(pat) == "string" and pat ~= "" then
                cells[#cells + 1] = { slot = (r - 1) * 4 + c, pat = pat }
            end
        end
    end
    if #cells == 0 then return false, "empty recipe grid" end

    local cellSlot = {}
    for _, cell in ipairs(cells) do cellSlot[cell.slot] = cell end

    local stashSide, stashed = nil, 0
    local function stashSlot(s)
        local d = turtle.getItemDetail(s)
        if not d then return true end
        if not stashSide then
            local order = {}
            if a.stash and a.stash ~= "none" then order[#order + 1] = a.stash end
            for _, dir in ipairs({ "front", "down", "up" }) do
                if dir ~= a.stash then order[#order + 1] = dir end
            end
            turtle.select(s)
            for _, dir in ipairs(order) do
                if dropTo(dir, nil) then
                    stashSide = dir
                    stashed = stashed + d.count
                    return true
                end
            end
            return false, "nowhere to stash " .. d.name
        end
        turtle.select(s)
        local ok, err = dropTo(stashSide, nil)
        if ok then stashed = stashed + d.count end
        return ok, err
    end

    -- 1. stash everything that does not match any recipe cell (this also frees
    --    cell slots that hold the wrong item)
    for s = 1, 16 do
        local d = turtle.getItemDetail(s)
        if d then
            local matches = false
            for _, cell in ipairs(cells) do
                if nameMatches(d.name, cell.pat) then matches = true break end
            end
            if not matches then
                local ok, err = stashSlot(s)
                if not ok then return false, err end
            end
        end
    end

    -- 2. put one matching item into every empty cell
    for _, cell in ipairs(cells) do
        local have = turtle.getItemDetail(cell.slot)
        if not (have and nameMatches(have.name, cell.pat)) then
            local src
            for s = 1, 16 do
                local d = turtle.getItemDetail(s)
                if d and nameMatches(d.name, cell.pat) then src = s break end
            end
            if not src then
                return false, "missing item: " .. cell.pat
            end
            turtle.select(src)
            if not turtle.transferTo(cell.slot, 1) then
                return false, "could not arrange " .. cell.pat
            end
        end
    end

    -- 3. merge leftover ingredients into their cell if there is room,
    --    stash anything still in the way
    for s = 1, 16 do
        local d = turtle.getItemDetail(s)
        if d and not cellSlot[s] then
            local target
            for _, cell in ipairs(cells) do
                if nameMatches(d.name, cell.pat) then
                    local t = turtle.getItemDetail(cell.slot)
                    if t and t.count < 64 then target = cell.slot break end
                end
            end
            if target then
                turtle.select(s)
                turtle.transferTo(target)
            else
                local ok, err = stashSlot(s)
                if not ok then return false, err end
            end
        end
    end

    -- 4. craft
    local before = invTotal()
    turtle.select(cells[1].slot)
    local times = tonumber(a.times) or 64
    local ok, err = turtle.craft(times)

    -- 5. get the stashed items back (chest or ground)
    local recovered = 0
    if stashSide and stashed > 0 then
        local beforeSuck = invTotal()
        turtle.select(1)
        for _ = 1, 64 do
            if stopFlag then break end
            if not suckFrom(stashSide) then break end
        end
        recovered = invTotal() - beforeSuck
    end
    dirtyState = true
    flushBlocks()

    local inv, out = invList(), {}
    local seenNames = {}
    for _, e in ipairs(inv) do
        if not seenNames[e.name] then seenNames[e.name] = true end
    end
    local data = {
        inv = inv, out = out, stashed = stashed, recovered = recovered,
        crafted = invTotal() - before,
    }
    if not ok then
        local extra = ""
        if stashed > 0 then
            extra = string.format(" (stashed %d, got %d back)", stashed,
                recovered)
        end
        return false, (err or "craft failed") .. extra, data
    end
    local summary = string.format("crafted %d item(s)", data.crafted)
    if stashed > 0 then
        summary = summary .. string.format(", stashed %d, recovered %d",
            stashed, recovered)
    end
    if recovered < stashed then
        summary = summary .. " - WARNING: " ..
            tostring(stashed - recovered) .. " item(s) not recovered!"
    end
    return true, summary, data
end

-- ----------------------------------------------------------------- jobs ----
local function runCmd(cmd, a)
    a = a or {}

    -- movement ------------------------------------------------------------- --
    if cmd == "forward" or cmd == "back" or cmd == "up" or cmd == "down" then
        local ok, err = move(cmd, false)
        return ok, err
    end
    if cmd == "turnLeft" then turnLeft() return true end
    if cmd == "turnRight" then turnRight() return true end

    -- block interaction ---------------------------------------------------- --
    if cmd == "dig" then
        local prev = scanMode
        if prev == "off" then scanMode = "walls" end
        local ok, err = digBlock(resolveDir(a.dir))
        scanMode = prev
        return ok, err
    end
    if cmd == "place" then
        local dir = resolveDir(a.dir)
        local d = turtle.getItemDetail()
        local tx, ty, tz = targetOf(dir)
        local fn = dir == "up" and turtle.placeUp or
            dir == "down" and turtle.placeDown or turtle.place
        local ok, err = fn(a.text)
        if ok and d then addBlock(tx, ty, tz, d.name) end
        dirtyState = true
        return ok, err
    end
    if cmd == "attack" then
        local dir = resolveDir(a.dir)
        local fn = dir == "up" and turtle.attackUp or
            dir == "down" and turtle.attackDown or turtle.attack
        local ok, err = fn()
        return ok, err
    end
    if cmd == "detect" then
        local dir = resolveDir(a.dir)
        local fn = dir == "up" and turtle.detectUp or
            dir == "down" and turtle.detectDown or turtle.detect
        return true, "ok", { solid = fn() }
    end
    if cmd == "inspect" then
        local dir = resolveDir(a.dir)
        local name = doInspect(dir)
        if name then
            local tx, ty, tz = targetOf(dir)
            addBlock(tx, ty, tz, name)
        end
        return true, name and "ok" or "no block", name and { name = name }
    end
    if cmd == "scan" then
        -- full surroundings snapshot: up, down and all four walls.
        -- forget what we already reported so EVERY cell is re-sent -
        -- this also fixes rescanning after "clear map" on the dashboard
        seen, seenCount = {}, 0
        scanSides(true)
        flushBlocks()
        dirtyState = true
        return true, "scanned surroundings"
    end

    -- inventory ------------------------------------------------------------- --
    if cmd == "select" then
        local slot = tonumber(a.slot)
        if not slot or slot < 1 or slot > 16 then return false, "bad slot" end
        turtle.select(slot)
        dirtyState = true
        return true, "slot " .. slot
    end
    if cmd == "drop" or cmd == "suck" then
        local dir = resolveDir(a.dir)
        local count = tonumber(a.count) or nil
        local fn
        if cmd == "drop" then
            fn = dir == "up" and turtle.dropUp or
                dir == "down" and turtle.dropDown or turtle.drop
        else
            fn = dir == "up" and turtle.suckUp or
                dir == "down" and turtle.suckDown or turtle.suck
        end
        local ok, err = fn(count)
        dirtyState = true
        return ok, err
    end
    if cmd == "refuel" then
        local target = tonumber(a.min) or
            math.floor(turtle.getFuelLimit() * 0.6)
        local before = turtle.getFuelLevel()
        if before == "unlimited" then return true, "unlimited" end
        local got = refuelScan(target)
        local after = turtle.getFuelLevel()
        if after >= target then
            return true, string.format("fuel %d -> %d", before, after)
        end
        return got and after > before, got and "not enough fuel items"
            or "no fuel in inventory"
    end

    -- navigation ------------------------------------------------------------ --
    if cmd == "calibrate" then
        local x, y, z = tonumber(a.x), tonumber(a.y), tonumber(a.z)
        if not x or not y or not z then return false, "need x, y, z" end
        pos.x, pos.y, pos.z = x, y, z
        known = true
        if a.facing ~= nil then
            local f = tonumber(a.facing) or ({ north = 0, east = 1,
                south = 2, west = 3 })[tostring(a.facing):lower()]
            if f then facing = f % 4 end
        end
        dirtyState = true
        saveLocal()
        return true, string.format("calibrated %d,%d,%d", x, y, z)
    end
    if cmd == "sethome" then
        home = { x = pos.x, y = pos.y, z = pos.z }
        dirtyState = true
        saveLocal()
        return true, "home set"
    end
    if cmd == "setfarm" then
        local here = { x = pos.x, y = pos.y, z = pos.z }
        if not farmA or farmB then
            -- first click (or restart after both corners were set)
            farmA, farmB = here, nil
            fcur = { lane = 0, cell = 0 }
            dirtyState = true
            saveLocal()
            return true, string.format(
                "farm corner A at %d,%d,%d - drive to the opposite corner and setfarm again",
                here.x, here.y, here.z)
        end
        -- second click: the marked rectangle is the whole field
        farmB = here
        fcur = { lane = 0, cell = 0 }
        dirtyState = true
        saveLocal()
        local w = math.abs(farmB.x - farmA.x) + 1
        local l = math.abs(farmB.z - farmA.z) + 1
        return true, string.format("field %dx%d marked (%d,%d)-(%d,%d)",
            w, l, farmA.x, farmA.z, farmB.x, farmB.z)
    end
    if cmd == "home" then
        if not home then return false, "no home set" end
        goTo(home.x, home.y, home.z)
        return true, "home"
    end
    if cmd == "goto" then
        local x, y, z = tonumber(a.x), tonumber(a.y), tonumber(a.z)
        if not x or not y or not z then return false, "need x, y, z" end
        local prev = scanMode
        if a.scan then scanMode = a.scan end
        goTo(x, y, z)
        scanMode = prev
        flushBlocks()
        return true, string.format("at %d,%d,%d", pos.x, pos.y, pos.z)
    end

    -- mining ---------------------------------------------------------------- --
    if cmd == "tunnel" then
        local len = math.max(1, math.min(1024, tonumber(a.len) or 16))
        local tall = a.tall ~= false
        scanMode = a.scan or "walls"
        local sx, sy, sz = pos.x, pos.y, pos.z
        for i = 1, len do
            checkStop()
            moveStrict("forward")
            if scanMode ~= "off" then
                if tall then digBlock("up") end
                scanSides(scanMode == "all")
            end
            if i % 5 == 0 then
                flushBlocks()
                dirtyState = true
            end
        end
        if a.ret then goTo(sx, sy, sz) end
        scanMode = "off"
        flushBlocks()
        dirtyState = true
        return true, string.format("tunneled %d blocks", len)
    end

    if cmd == "mine" then
        local w = math.max(1, math.min(64, tonumber(a.w) or 3))
        local l = math.max(1, math.min(64, tonumber(a.l) or 16))
        local depth = math.max(1, math.min(64, tonumber(a.d) or 1))
        local tall = a.tall ~= false
        scanMode = a.scan or "walls"
        local sx, sy, sz = pos.x, pos.y, pos.z
        local total = w * l * depth
        if turtle.getFuelLevel() ~= "unlimited" and
            turtle.getFuelLevel() < total then
            scanMode = "off"
            return false, string.format("need ~%d fuel, have %d", total,
                turtle.getFuelLevel())
        end
        local function goRel(dx, dy, dz)
            local tx, ty, tz = sx + dx, sy + dy, sz + dz
            local guard = 0
            while pos.y ~= ty do
                moveStrict(pos.y < ty and "up" or "down")
                guard = guard + 1
                if guard > 128 then error("descend failed", 0) end
            end
            while pos.x ~= tx do stepTo(pos.x < tx and 1 or 3) end
            while pos.z ~= tz do stepTo(pos.z < tz and 2 or 0) end
        end
        for layer = 0, depth - 1 do
            for col = 0, w - 1 do
                local rev = (col % 2 == 1)
                for i = 0, l - 1 do
                    checkStop()
                    local lz = rev and (l - 1 - i) or i
                    goRel(col, -layer, lz)
                    if scanMode ~= "off" then
                        if tall then digBlock("up") end
                        scanSides(scanMode == "all")
                    end
                end
            end
            if layer < depth - 1 then moveStrict("down") end
            flushBlocks()
            dirtyState = true
        end
        if a.ret ~= false then goRel(0, 0, 0) end
        scanMode = "off"
        flushBlocks()
        dirtyState = true
        return true, string.format("mined %dx%dx%d", w, l, depth)
    end

    -- auto mining: grid around home, chase ores, home when the bag is full - --
    if cmd == "autoMine" then
        if not home then
            return false, "set home first (sethome)"
        end
        local tall = a.tall ~= false
        scanMode = a.scan or "walls"
        local span = tonumber(a.span) or 15    -- half-width of the grid box
        if span < 1 then span = 1 elseif span > 64 then span = 64 end
        local steps = 0
        local fails = 0
        -- fresh detection only: old sightings may long be mined out
        oreTargets = {}
        local function full()
            for i = 1, 16 do
                if not turtle.getItemDetail(i) then return false end
            end
            return true
        end
        local function nearestOre()
            local bx, by, bz, bd
            for _, c in pairs(oreTargets) do
                local d = math.abs(c.x - pos.x) + math.abs(c.y - pos.y)
                    + math.abs(c.z - pos.z)
                if not bd or d < bd then
                    bx, by, bz, bd = c.x, c.y, c.z, d
                end
            end
            return bx, by, bz
        end
        -- serpentine lanes centred on home: lane k runs east on even k and
        -- west on odd k while z zig-zags, y walks its own zig-zag per layer,
        -- so the turtle always grinds a box around home instead of one long
        -- tunnel that wanders out of loaded chunks (which freezes the turtle
        -- and drops the websocket)
        local LAYERY = { 0, -1, 1, -2, 2 }
        local function zig(m)
            if m == 0 then return 0 end
            local s = math.ceil(m / 2)
            if m % 2 == 1 then return s end
            return -s
        end
        local function patternCell()
            local g = gcur
            local x
            if g.lane % 2 == 1 then
                x = home.x + span - g.cell
            else
                x = home.x - span + g.cell
            end
            return x, home.y + (LAYERY[g.layer + 1] or 0),
                   home.z + zig(g.lane)
        end
        local function advance()
            local g = gcur
            g.cell = g.cell + 1
            if g.cell > span * 2 then
                g.cell = 0
                g.lane = g.lane + 1
                if g.lane > span * 2 then
                    g.lane = 0
                    g.layer = g.layer + 1
                    if g.layer >= #LAYERY then
                        g.layer = 0
                        log("auto-mine: grid covered - restarting pattern",
                            "info")
                    end
                end
            end
            dirtyState = true
        end
        log("auto-mine: grid around home, ores first, then home", "ok")
        while true do
            checkStop()
            -- top up fuel every lap (refuel no-ops once above target)
            pcall(runCmd, "refuel", { min = 64 })
            if full() then
                flushBlocks()
                log("auto-mine: inventory full - heading home", "warn")
                status = "autoMine: homing"
                dirtyState = true
                local dist = math.abs(home.x - pos.x)
                    + math.abs(home.y - pos.y) + math.abs(home.z - pos.z) + 16
                pcall(runCmd, "refuel", { min = dist })
                goTo(home.x, home.y, home.z)
                scanMode = "off"
                flushBlocks()
                pushState()
                return true, string.format("full - homed at %d,%d,%d",
                    pos.x, pos.y, pos.z)
            end
            local ox, oy, oz = nearestOre()
            if ox then
                status = "autoMine: chasing ore"
                dirtyState = true
                -- goTo digs through everything; landing inside the ore cell
                -- is what actually mines the ore block
                local okOre, errOre = pcall(goTo, ox, oy, oz)
                if okOre then
                    -- we occupy that cell now, so it is air by definition;
                    -- recording it clears the target and corrects the map
                    addBlock(ox, oy, oz, "minecraft:air")
                else
                    oreTargets[bkey(ox, oy, oz)] = nil
                    log("ore unreachable: " .. tostring(errOre), "warn")
                end
            else
                local tx, ty, tz = patternCell()
                if pos.x == tx and pos.y == ty and pos.z == tz then
                    -- standing in the pattern cell: clear it, scan, advance
                    status = "autoMine: grid mining"
                    dirtyState = true
                    fails = 0
                    if tall then digBlock("up") end
                    steps = steps + 1
                    -- peek around the side walls for embedded ores
                    if scanMode ~= "off" and steps % 4 == 3 then
                        scanSides(false)
                    end
                    advance()
                else
                    status = "autoMine: grid walking"
                    dirtyState = true
                    local okM, errM = pcall(goTo, tx, ty, tz)
                    if okM then
                        fails = 0
                    else
                        -- unbreakable cell: skip it, but bail out instead of
                        -- spinning in place if the pattern can't progress
                        fails = fails + 1
                        if fails > 4 then
                            return false, "grid blocked: " .. tostring(errM)
                        end
                        advance()
                    end
                end
            end
        end
    end

    -- farming: harvest mature crops + replant, strictly inside the marked field
    if cmd == "farm" then
        if not farmA or not farmB then
            return false, "mark the field first (setfarm at both corners)"
        end
        if not home then
            return false, "set home first (sethome)"
        end
        scanMode = "off"
        -- normalized bounds: corners are the crop layer, order independent
        local x1 = math.min(farmA.x, farmB.x)
        local x2 = math.max(farmA.x, farmB.x)
        local z1 = math.min(farmA.z, farmB.z)
        local z2 = math.max(farmA.z, farmB.z)
        local y = farmA.y                    -- crop layer (stands on farmland)
        local py = y + 1                     -- path layer, one above the crops
        local w, l = x2 - x1 + 1, z2 - z1 + 1
        if fcur.cell >= w or fcur.lane >= l then
            fcur = { lane = 0, cell = 0 }    -- field shrank / new mark: restart
        end
        local harvested, planted, missed, laps = 0, 0, 0, 0
        local fails = 0
        -- maturity per known crop; unknown age crops default to max 7
        local CROP_MAX = {
            ["minecraft:wheat"] = 7,
            ["minecraft:carrots"] = 7,
            ["minecraft:potatoes"] = 7,
            ["minecraft:beetroot"] = 3,
            ["minecraft:nether_wart"] = 3,
        }
        local SEEDY = { ["minecraft:carrots"] = true,
                        ["minecraft:potatoes"] = true }
        local function isCrop(info)
            if type(info) ~= "table" then return false end
            local st = type(info.state) == "table" and info.state or {}
            return tonumber(st.age) ~= nil or CROP_MAX[info.name] ~= nil
        end
        local function full()
            for i = 1, 16 do
                if not turtle.getItemDetail(i) then return false end
            end
            return true
        end
        -- exact seed for a harvested crop, else nil (never cross-plant)
        local function seedSlot(crop)
            local want
            if SEEDY[crop] then
                want = crop                      -- carrots/potatoes plant as-is
            elseif crop == "minecraft:wheat" then
                want = "minecraft:wheat_seeds"
            elseif crop == "minecraft:beetroot" then
                want = "minecraft:beetroot_seeds"
            else
                want = crop .. "_seeds"          -- modded convention
            end
            for i = 1, 16 do
                local d = turtle.getItemDetail(i)
                if d and d.name == want then return i end
            end
            return nil
        end
        -- any plantable we carry: fills bare soil with whatever we have
        local function anySeed()
            for i = 1, 16 do
                local d = turtle.getItemDetail(i)
                if d and (d.name:find("_seeds$") or SEEDY[d.name]) then
                    return i
                end
            end
            return nil
        end
        -- seed item -> the block it grows into (map stays honest)
        local function cropOf(seedName)
            if seedName == "minecraft:wheat_seeds" then return "minecraft:wheat" end
            if seedName == "minecraft:beetroot_seeds" then return "minecraft:beetroot" end
            if seedName:find("_seeds$") then
                return (seedName:gsub("_seeds$", ""))
            end
            return seedName                     -- carrots / potatoes
        end
        local function farmCell()
            local g = fcur
            if g.cell >= w or g.lane >= l then  -- field re-marked mid-job
                fcur = { lane = 0, cell = 0 }
                g = fcur
            end
            local cx
            if g.lane % 2 == 1 then cx = x2 - g.cell else cx = x1 + g.cell end
            return cx, z1 + g.lane
        end
        local function advance()
            local g = fcur
            g.cell = g.cell + 1
            if g.cell >= w then
                g.cell = 0
                g.lane = g.lane + 1
                if g.lane >= l then
                    g.lane = 0
                    laps = laps + 1
                    log(string.format("farm: lap %d done (%d harvested, %d planted)",
                        laps, harvested, planted), "info")
                end
            end
            dirtyState = true
        end
        -- walk above the field without digging: a roof or stray block gets
        -- reported (map + clear error), never chewed through
        local function flyTo(x, y, z)
            while pos.y ~= y do
                local dy = y > pos.y and 1 or -1
                if not move(dy > 0 and "up" or "down", false) then
                    return false, "field path blocked at " ..
                        bkey(pos.x, pos.y + dy, pos.z)
                end
            end
            while pos.x ~= x do
                local dx = x > pos.x and 1 or -1
                faceTo(dx > 0 and 1 or 3)
                if not move("forward", false) then
                    local f = FWD[facing]
                    return false, "field path blocked at " ..
                        bkey(pos.x + f.x, pos.y, pos.z + f.z)
                end
            end
            while pos.z ~= z do
                local dz = z > pos.z and 1 or -1
                faceTo(dz > 0 and 2 or 0)
                if not move("forward", false) then
                    local f = FWD[facing]
                    return false, "field path blocked at " ..
                        bkey(pos.x + f.x, pos.y, pos.z + f.z)
                end
            end
            return true
        end
        -- reach the field: the y leg runs wherever the turtle currently is,
        -- then the horizontal legs run on the path layer (above the crops)
        local okP, errP = pcall(goTo, x1, py, z1)
        if not okP then
            return false, "cannot reach the field: " .. tostring(errP)
        end
        local hasC, corner = turtle.inspectDown()
        if hasC and not isCrop(corner) then
            return false, string.format(
                "corner is %s, not a field (mark corners on the crops/soil)",
                tostring(corner.name))
        end
        log(string.format("farm: %dx%d field at %d,%d - harvest mature, replant",
            w, l, x1, z1), "ok")
        while true do
            checkStop()
            pcall(runCmd, "refuel", { min = 64 })
            if full() then
                flushBlocks()
                log("farm: inventory full - heading home", "warn")
                status = "farm: homing"
                dirtyState = true
                local dist = math.abs(home.x - pos.x) + math.abs(home.y - pos.y)
                    + math.abs(home.z - pos.z) + 16
                pcall(runCmd, "refuel", { min = dist })
                goTo(home.x, home.y, home.z)
                scanMode = "off"
                flushBlocks()
                pushState()
                return true, string.format(
                    "full - homed at %d,%d,%d (harvested %d, planted %d)",
                    pos.x, pos.y, pos.z, harvested, planted)
            end
            local cx, cz = farmCell()
            local okG, errG = flyTo(cx, py, cz)
            if okG then
                fails = 0
                local has, info = turtle.inspectDown()
                if has and isCrop(info) then
                    local st = type(info.state) == "table" and info.state or {}
                    local age = tonumber(st.age)
                    local maxAge = CROP_MAX[info.name]
                    local mature
                    if age == nil then
                        mature = maxAge ~= nil       -- no age state = ready
                    else
                        mature = age >= (maxAge or 7)
                    end
                    if mature then
                        local slot = seedSlot(info.name)
                        if slot then
                            -- only take what we can put back: never strip a
                            -- crop we carry no seed for
                            status = "farm: harvesting"
                            dirtyState = true
                            if turtle.digDown() then
                                harvested = harvested + 1
                                addBlock(cx, y, cz, "minecraft:air")
                            end
                            turtle.select(slot)
                            if turtle.placeDown() then
                                planted = planted + 1
                                addBlock(cx, y, cz, info.name)
                            else
                                missed = missed + 1
                            end
                        else
                            missed = missed + 1   -- out of seeds: leave standing
                        end
                    else
                        status = "farm: watching crops"
                        dirtyState = true
                    end
                elseif not has then
                    -- bare crop cell: plant it if the soil below accepts
                    local slot = anySeed()
                    if slot then
                        local d = turtle.getItemDetail(slot)
                        turtle.select(slot)
                        if turtle.placeDown() then
                            planted = planted + 1
                            addBlock(cx, y, cz, cropOf(d.name))
                        end
                        status = "farm: planting"
                        dirtyState = true
                    end
                end
                -- anything else (stone, water, path) is left alone
                flushBlocks()
                advance()
            else
                fails = fails + 1
                if fails > 4 then
                    return false, "field blocked: " .. tostring(errG)
                end
                advance()
            end
        end
    end

    -- dumping --------------------------------------------------------------- --
    if cmd == "dump" then
        local dir = resolveDir(a.dir)
        local keep = a.keep or {}
        local dropped, failed = 0, nil
        for i = 1, 16 do
            checkStop()
            local d = turtle.getItemDetail(i)
            if d then
                local keepIt = false
                for _, pat in ipairs(keep) do
                    if nameMatches(d.name, pat) then keepIt = true break end
                end
                if not keepIt then
                    turtle.select(i)
                    local ok, err = dropTo(dir, nil)
                    if ok then dropped = dropped + d.count
                    else failed = err end
                end
            end
        end
        dirtyState = true
        if dropped == 0 and failed then return false, failed end
        return true, string.format("dumped %d items%s", dropped,
            failed and (" (" .. failed .. ")") or "")
    end

    -- automation: mine + refuel + dump, repeat until stopped ---------------- --
    if cmd == "cycle" then
        local w = math.max(1, math.min(64, tonumber(a.w) or 3))
        local l = math.max(1, math.min(64, tonumber(a.l) or 16))
        local depth = math.max(1, math.min(64, tonumber(a.d) or 1))
        local dumpDir = resolveDir(a.dump or "front")
        local keep = a.keep or {}
        local times = tonumber(a.times) or -1
        local need = math.floor(w * l * depth * 1.5) + 64
        local n, mined = 0, 0
        while times < 0 or n < times do
            checkStop()
            status = "cycle: refuel"
            dirtyState = true
            runCmd("refuel", { min = need })
            status = "cycle: mine"
            dirtyState = true
            local ok, msg = runCmd("mine", { w = w, l = l, d = depth,
                tall = a.tall, ret = true, scan = a.scan })
            if not ok then return false, "mine failed: " .. tostring(msg) end
            mined = mined + w * l * depth
            checkStop()
            status = "cycle: dump"
            dirtyState = true
            runCmd("dump", { dir = dumpDir, keep = keep })
            n = n + 1
            flushBlocks()
            dirtyState = true
        end
        return true, string.format("cycle: %d round(s), ~%d blocks", n, mined)
    end

    -- crafting --------------------------------------------------------------- --
    if cmd == "craft" then
        local ok, msg, data = craftJob(a)
        return ok, msg, data
    end

    -- arbitrary code --------------------------------------------------------- --
    if cmd == "lua" then
        local code = a.code
        if not code or code == "" then return false, "no code" end
        local fn, err = load(code, "remote", "t", _ENV)
        if not fn then return false, tostring(err) end
        local prints = {}
        local oldPrint = print
        print = function(...)
            local parts = {}
            for i = 1, select("#", ...) do
                parts[#parts + 1] = tostring(select(i, ...))
            end
            prints[#prints + 1] = table.concat(parts, " ")
            if #prints > 20 then table.remove(prints, 1) end
        end
        local results = table.pack(pcall(fn))
        print = oldPrint
        local n = results.n
        local rets = {}
        for i = 2, results.n do rets[#rets + 1] = tostring(results[i]) end
        if results[1] then
            return true, #rets > 0 and table.concat(rets, " ") or "ok",
                { prints = prints, returns = rets }
        end
        return false, tostring(results[2]), { prints = prints, n = n }
    end

    return false, "unknown command: " .. tostring(cmd)
end

-- --------------------------------------------------------------- coroutines --
local function handleMessage(raw)
    local m = textutils.unserializeJSON(raw)
    if not m or type(m) ~= "table" then return end
    if m.t == "cmd" then
        if m.cmd == "stop" then
            stopFlag = true
            jobs = {}
            push({ t = "result", seq = m.seq, ok = true, msg = "stopping" })
            log("stop requested", "warn")
        else
            jobs[#jobs + 1] = { seq = m.seq, cmd = m.cmd, args = m.args }
        end
    elseif m.t == "welcome" then
        connected = true
        seen = {}
        seenCount = 0
        status = "idle"
        log("connected as " .. tostring(m.name or NAME), "ok")
        pushState()
        flushBlocks()
    elseif m.t == "error" then
        error(tostring(m.msg), 0)
    end
end

--- Sole websocket writer + event pump. Returning ends the session.
local function reader()
    local tick = 0
    local timer = os.startTimer(1)
    while true do
        local ev = { os.pullEvent() }
        local e = ev[1]
        if e == "hud_flush" then
            if not flushOutbox() then return end
        elseif e == "timer" and ev[2] == timer then
            tick = tick + 1
            -- push state when something changed (<=1s latency while moving),
            -- plus a 10s heartbeat even when idle
            if dirtyState or tick % 10 == 0 then
                pushState()
                saveLocal()
            end
            flushBlocks()
            if not flushOutbox() then return end
            renderScreen()
            timer = os.startTimer(1)
        elseif e == "websocket_message" and ev[2] == WS_URL then
            handleMessage(ev[3])
            if not flushOutbox() then return end
        elseif (e == "websocket_closed" or e == "websocket_failure") and
            ev[2] == WS_URL then
            return
        end
    end
end

local function worker()
    while true do
        local job
        if #jobs > 0 then job = table.remove(jobs, 1) end
        if job then
            stopFlag = false
            status = job.cmd
            dirtyState = true
            renderScreen()
            local packed = { pcall(runCmd, job.cmd, job.args) }
            local ok, msg, data
            if packed[1] then
                ok, msg, data = packed[2], packed[3], packed[4]
            else
                ok, msg = false, tostring(packed[2])
            end
            status = ok and "idle" or "error"
            push({ t = "result", seq = job.seq, ok = ok and true or false,
                   msg = msg or "", data = data })
            flushBlocks()
            dirtyState = true
            renderScreen()
            if not ok then
                -- bumping a wall while driving is normal feedback, not a crash
                local lvl = tostring(msg):find("obstruct", 1, true)
                    and "warn" or "error"
                log(tostring(job.cmd) .. ": " .. tostring(msg), lvl)
            end
        else
            sleep(0.1)
        end
    end
end

-- ----------------------------------------------------------------- session --
local function waitForWelcome()
    -- send hello directly so it is always the first frame on the wire,
    -- ahead of any queued log lines (those flush once reader() starts)
    ws.send(textutils.serializeJSON(
        { t = "hello", token = TOKEN, name = NAME, cid = CID, ver = 1 }))
    local timer = os.startTimer(15)
    while true do
        local ev = { os.pullEvent() }
        local e = ev[1]
        if e == "websocket_message" and ev[2] == WS_URL then
            local m = textutils.unserializeJSON(ev[3])
            if m and m.t == "welcome" then
                handleMessage(ev[3])
                return
            elseif m and m.t == "error" then
                handleMessage(ev[3])
            end
        elseif e == "timer" and ev[2] == timer then
            error("server sent no welcome")
        elseif (e == "websocket_closed" or e == "websocket_failure") and
            ev[2] == WS_URL then
            error("connection closed")
        end
    end
end

local function session()
    local w, err = http.websocket(WS_URL)
    if not w then error(tostring(err), 0) end
    ws = w
    connected = false

    -- best effort gps fix (needs a wireless modem upgrade)
    local okGps, gx, gy, gz = pcall(gps.locate, 2)
    if okGps and gx then
        pos.x, pos.y, pos.z = gx, gy, gz
        known = true
        log(string.format("gps fix %d,%d,%d", gx, gy, gz), "ok")
    end
    if not gx then log("no gps fix - calibrate in the HUD", "warn") end

    waitForWelcome()
    parallel.waitForAny(reader, worker)
end

-- --------------------------------------------------------------------- run --
loadLocal()
print("Turtle HUD starting...")
print("server: " .. WS_URL)

local urlIdx = 1
local backoff = 1
while true do
    status = "connecting"
    renderScreen()
    local ok, err = pcall(session)
    connected = false
    jobs = {}
    stopFlag = false
    if ws then pcall(ws.close) end
    ws = nil
    outbox = {}
    -- cells queued at disconnect died with the outbox; forget what we
    -- "reported" so the next session re-sends them instead of skipping
    -- them forever (this was why bumped walls sometimes never rendered)
    seen, seenCount = {}, 0
    if not ok then
        status = "reconnecting"
        printError(tostring(err))
        log("disconnected: " .. tostring(err), "error")
        -- rotate endpoints: when the quick tunnel is dead its url has
        -- changed, so the next attempt goes through the permanent funnel
        urlIdx = urlIdx % #WS_URLS + 1
        WS_URL = WS_URLS[urlIdx]
        renderScreen()
        sleep(backoff)
        backoff = math.min(backoff * 2, 10)
    else
        urlIdx = 1
        WS_URL = WS_URLS[urlIdx]
        backoff = 1
        sleep(0.5)
    end
end
